### PR TITLE
fix: Videos doesn't work on iOS devices

### PR DESCRIPTION
**Pull request by moninm**
Fix issue 96 on iOS Video

### CODE REVIEW

**Comment by BenRamins** [comment]
@moninm, did this fix actually work for you? I thought it was this as well, and I made essentially the same fix, but the same problem persisted. Please let me know!

**Comment by moninm** [comment]
> @moninm, did this fix actually work for you? I thought it was this as well, and I made essentially the same fix, but the same problem persisted. Please let me know!

Yes, those changes fixed the issue.

**Comment by BenRamins** [comment]
@moninm sorry to bother you, but I was wondering if you cloned the repo and made your changes through patch package, or if you made your edits directly into the node_module installed in your project?

 I tried the latter approach, and then running `npm run buildall` but then that gives me an error:

```
ERROR in ./src/index.tsx 11:41
Module parse failed: Unexpected token (11:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import withSeeMore from './renderers/wrappers/withSeeMore'
|
> const ReactInstaStories = function (props: ReactInstaStoriesProps) {
|     let context: GlobalCtx = {
```

sorry for the noob question :)

**Comment by moninm** [comment]
It is browser specific behaviour. Mute is mandatory for autoplay on iOS device without user interaction. I think the best way is to add an overlay and manage mute/unmute by yourself.

**Pull request merged**
