### PR TITLE
The extra div was messing with the img styling removed it

### PR DESCRIPTION
**Pull request by rahulbansal16**

### CODE REVIEW

**Comment by rahulbansal16** [comment]
@mohitk05 can you please review it.

**Comment by NikosEfthias** [comment]
seems the repo is dead

**Comment by rahulbansal16** [comment]
I guess so. I have made a fork and pushing the code over there.

**Comment by mohitk05** [comment]
@rahulbansal16 Thanks for the PR! Was finding it difficult to pull out some time for this. PR looks good to me, can you revert the package name if you still wish to get this PR merged? I'll get that done asap.

**Comment by rahulbansal16** [comment]
@mohitk05 I have made the change here https://github.com/mohitk05/react-insta-stories/pull/99

**Pull request closed without merging**
